import streamlit as st
import streamlit_tags as stt
import pandas as pd
import requests

tags_data = {
    'Categorie': ['Cuisine origin', 'Diet type', 'Category', 'Occasion', 'Equipment'],
    'Tags': [['african',
        'american','amish mennonite','angolan','argentine',
        'asian','australian','austrian','beijing','belgian'
        'brazilian','british columbian','cajun','californian',
        'cambodian','canadian','cantonese','caribbean',
        'central american','chilean','chinese','colombian',
        'congolese','costa rican','creole','cuban',
        'czech','danish','dutch','ecuadorean',
        'egyptian','english','ethiopian','european',
        'filipino','finnish','french','georgian',
        'german','greek','guatemalan','hawaiian',
        'honduran','hunan','hungarian','icelandic',
        'indian','indonesian','iranian persian','iraqi',
        'irish','italian','japanese','jewish ashkenazi',
        'jewish sephardi','korean','laotian','lebanese',
        'libyan','malaysian','mexican','micro melanesia',
        'middle eastern','middle eastern main dish',
        'midwestern','mongolian','moroccan','namibian',
        'native american','nepalese','new zealand','nigerian',
        'north american','northeastern united states',
        'norwegian','oaxacan','ontario','pacific northwest',
        'pakistani','palestinian','pennsylvania dutch','peruvian',
        'polish','polynesian','portuguese','puerto rican',
        'quebec','russian','saudi arabian','scandinavian',
        'scottish','somalian','south african','south american',
        'south west pacific','southern united states',
        'southwestern united states','spanish','sudanese','swedish',
        'swiss','szechuan','tex mex','thai',
        'turkish','venezuelan','vietnamese','welsh'],
             ['dairy free','diabetic','dietary','egg free','eggs dairy',
        'free of something','gluten free','healthy','high calcium',
        'high fiber','high in something',
        'high in something diabetic friendly','high protein',
        'kosher','lactose','low calorie','low carb',
        'low cholesterol','low fat','low in something','low protein',
        'low saturated fat','low sodium','no shell fish','non alcoholic',
        'nut free','vegan','vegetarian','very low carbs'],
             ['appetizers','baking','beverages',
        'breakfast casseroles','breakfast eggs',
        'breakfast potatoes','brewing','broil','brownies',
        'burgers','cake fillings and frostings',
        'cakes','canning','casseroles','celebrity',
        'cheesecake','chutneys','clear soups','cobblers and crisps',
        'coffee cakes','college','comfort food','cookies and brownies',
        'cooking mixes','copycat','course','crock pot main dish',
        'crock pot slow cooker','crusts pastry dough 2',
        'cupcakes','curries','deep fry','desserts',
        'desserts easy','desserts fruit','dips','dips lunch snacks',
        'dips summer','drop cookies','fall','fillings and frostings chocolate',
        'finger food','flat shapes','from scratch','frozen desserts',
        'garnishes','granola and porridge','grilling','ham and bean soup',
        'hand formed cookies','heirloom historical','herb and spice mixes','ice cream',
        'inexpensive','infant baby friendly','jams and preserves','jellies',
        'kid friendly','lamb sheep main dish','lasagna','leftovers',
        'lunch','macaroni and cheese','main dish','main dish beef',
        'main dish chicken','main dish pasta','main dish pork','main dish seafood',
        'main ingredient','marinades and rubs','marinara sauce','mashed potatoes',
        'meatballs','meatloaf','muffins','mushroom soup',
        'no cook','novelty','number of servings','oamc freezer make ahead',
        'omelets and frittatas','one dish meal','pancakes and waffles','pasta rice and grains',
        'pasta salad','pies','pies and tarts','pitted fruit',
        'pizza','pot pie','pot roast','potluck',
        'preparation','prepared potatoes','presentation','puddings and mousses',
        'pumpkin bread','punch','quiche','quick breads',
        'ragu recipe contest','roast','roast beef comfort food','roast beef main dish',
        'rolled cookies','rolls biscuits','salad dressings','salsas',
        'saltwater fish','sandwiches','sauces','savory',
        'savory pies','savory sauces','scones','seafood',
        'seasonal','served cold','served hot','shakes',
        'shrimp main dish','side dishes','side dishes beans','simply potatoes',
        'smoothies','snacks','snacks kid friendly',
        'snacks sweet','sole and flounder','soul','soups stews',
        'spaghetti sauce','spicy','spreads','spring',
        'steam','stews','stews poultry','stir fry',
        'stocks','stuffings dressings','sugar cookies','summer',
        'sweet','sweet sauces','tarts','technique',
        'toddler friendly','tropical fruit','turkey burgers','vegetables',
        'veggie burgers','water bath','wings','winter'],
             ['april fools day','barbecue',
        'birthday','breakfast','brunch','camping',
        'chinese new year','christmas','cinco de mayo','cocktails',
        'dinner party','easter','fathers day','for 1 or 2',
        'for large groups','gifts','halloween','halloween cakes',
        'halloween cocktails','halloween cupcakes','hanukkah','holiday event',
        'independence day','kwanzaa','labor day','mardi gras carnival',
        'memorial day','mothers day','new years','passover',
        'picnic','ramadan','romantic','rosh hashanah',
        'served hot new years','st patricks day','superbowl','taste mood',
        'thanksgiving','to go','valentines day','wedding','weeknight'],
             ['bread machine',
        'brown bag','dehydrator','food processor blender','freezer',
        'microwave','mixer','oven','pressure canning',
        'pressure cooker','refrigerator','small appliance','smoker',
        'stove top','time to make','unprocessed freezer']]
}

df_tags = pd.DataFrame(tags_data)

# Exemple de liste d'ingrédients
ingredients_list = ['acorn squash',
 'active dry yeast',
 'adobo sauce',
 'agave nectar',
 'alfredo sauce',
 'allbran cereal',
 'allpurpose flour',
 'allspice',
 'almond',
 'almond extract',
 'almond flour',
 'almond milk',
 'almond paste',
 'aluminum foil',
 'amaretto',
 'american cheese',
 'ancho chili',
 'anchovy',
 'andouille sausage',
 'angel food cake',
 'angel hair pasta',
 'anise',
 'apple',
 'apple cider',
 'apple cider vinegar',
 'apple juice',
 'applesauce',
 'apricot',
 'preserve',
 'apricot nectar',
 'arborio rice',
 'arrowroot',
 'artichoke heart',
 'arugula',
 'asiago cheese',
 'asparagus',
 'avocado',
 'bacon',
 'bacon dripping',
 'baguette',
 'baked bean',
 'baking cocoa',
 'baking mix',
 'potato',
 'baking powder',
 'baking soda',
 'balsamic vinegar',
 'bamboo shoot',
 'banana',
 'barbecue sauce',
 'barley',
 'basil',
 'basmati rice',
 'bay leaf',
 'bean',
 'bean sprout',
 'beef',
 'beef brisket',
 'beef broth',
 'beef chuck',
 'beef roast',
 'beef stew meat',
 'beef stock',
 'beer',
 'beet',
 'bell pepper',
 'berry',
 'biscuit',
 'bisquick baking mix',
 'bittersweet chocolate',
 'black bean',
 'black olive',
 'black pepper',
 'blackberry',
 'blackeyed pea',
 'blue cheese',
 'blue curacao',
 'blueberry',
 'bok choy',
 'boneless pork loin',
 'boneless skinless chicken breast',
 'bouillon cube',
 'bourbon whiskey',
 'bow tie pasta',
 'bran',
 'brandy',
 'bratwurst',
 'bread',
 'breadcrumb',
 'breakfast sausage',
 'brie cheese',
 'broccoli',
 'broth',
 'brown mustard',
 'brown rice',
 'brown sugar',
 'brownie mix',
 'brussels sprout',
 'buckwheat flour',
 'bulgur',
 'butter',
 'butter bean',
 'buttermilk',
 'butternut squash',
 'butterscotch pudding',
 'butterscotch schnapps',
 'button mushroom',
 'cabbage',
 'caesar salad dressing',
 'cajun seasoning',
 'cake mix',
 'candy sprinkle',
 'canned tomato',
 'canned whole cranberry sauce',
 'cannellini bean',
 'canola oil',
 'cantaloupe',
 'caper',
 'capsicum',
 'caramel',
 'caraway seed',
 'carbonated beverage',
 'cardamom',
 'carrot',
 'cashew',
 'caster sugar',
 'catfish',
 'cauliflower',
 'cayenne pepper',
 'celery',
 'celery seed',
 'centercut pork loin chop',
 'chambord raspberry liquor',
 'champagne',
 'cheddar cheese',
 'cheese',
 'cheese blend',
 'cherry',
 'cherry tomato',
 'chicken',
 'chicken breast',
 'chicken broth',
 'chicken drumstick',
 'chicken leg',
 'chicken liver',
 'chicken piece',
 'chicken stove top stuffing mix',
 'chicken tender',
 'chicken thigh',
 'chicken wing',
 'chickpea',
 'chiken borth',
 'chile',
 'chiles',
 'chili bean',
 'chili paste',
 'chili powder',
 'chili sauce',
 'chiligarlic sauce',
 'chinese five spice powder',
 'chipotle chile',
 'chive',
 'chocolate',
 'chocolate cake mix',
 'chocolate candy',
 'chocolate chip',
 'chocolate flavored syrup',
 'chorizo sausage',
 'chow mein noodle',
 'chutney',
 'cilantro',
 'cinnamon',
 'clam',
 'clam juice',
 'clove',
 'club soda',
 'coarse ground pepper',
 'cocoa',
 'cocoa powder',
 'coconut',
 'coconut cream',
 'coconut extract',
 'coconut milk',
 'coconut rum',
 'cod',
 'coffee',
 'coffee powder',
 'cognac',
 'cointreau liqueur',
 'colby cheese',
 'coleslaw',
 'condensed cheddar cheese soup',
 'condensed milk',
 'confectioner sugar',
 'cooked shrimp',
 'cooking oil',
 'cooking spray',
 'coriander',
 'coriander seed',
 'corn',
 'corn chip',
 'corn flake',
 'corn kernel',
 'corn oil',
 'corn syrup',
 'corn tortilla chip',
 'cornbread',
 'cornmeal',
 'cornstarch',
 'cottage cheese',
 'countrystyle boneless pork rib',
 'couscous',
 'crabmeat',
 'cracked pepper',
 'cracker',
 'craisins',
 'cranberry',
 'cranberry sauce',
 'cream',
 'cream cheese',
 'cream of celery soup',
 'cream of chicken soup',
 'cream of mushroom soup',
 'cream of tartar',
 'creamed corn',
 'creme de cacao',
 'creme fraiche',
 'creole seasoning',
 'crescent roll',
 'crisco allvegetable shortening',
 'crisp rice cereal',
 'crouton',
 'crushed pineapple',
 'crusty bread',
 'cucumber',
 'cumin',
 'currant',
 'curry',
 'curry leaf',
 'curry paste',
 'curry powder',
 'dark chocolate',
 'date',
 'deli ham',
 'deli turkey',
 'devil food cake mix',
 'diced tomato',
 'dijon mustard',
 'dill',
 'dill pickle',
 'dill seed',
 'dill sprig',
 'dill weed',
 'double cream',
 'dressing',
 'dried apricot half',
 'dried fruit',
 'dried onion flake',
 'dried oregano leaf',
 'dried parsley flake',
 'dried red chili pepper',
 'dry mustard',
 'dry roasted peanut',
 'dry wine',
 'edamame',
 'egg',
 'egg noodle',
 'egg substitute',
 'eggnog',
 'eggplant',
 'elbow macaroni',
 'enchilada sauce',
 'english muffin',
 'espresso',
 'evaporated milk',
 'extra lean ground beef',
 'fat',
 'fennel',
 'fennel bulb',
 'fennel seed',
 'fenugreek leaf',
 'feta cheese',
 'fettuccine',
 'fig',
 'firm tofu',
 'fish',
 'fish fillet',
 'fish sauce',
 'fish stock',
 'fivespice powder',
 'flaked coconut',
 'flank steak',
 'flax seed',
 'flour',
 'flour tortilla',
 'fontina',
 'food coloring',
 'frangelico',
 'fresh black pepper',
 'fresh raspberry',
 'frosting',
 'frozen corn',
 'frozen cut green bean',
 'fruit',
 'fruit juice',
 'fusilli',
 'garbanzo bean',
 'garlic',
 'garlic clove',
 'garlic powder',
 'gelatin',
 'ghee',
 'gin',
 'ginger',
 'ginger ale',
 'gingerroot',
 'gluten',
 'glutenfree cornflour',
 'glutenfree flour',
 'goat cheese',
 'gold leaf foil',
 'golden seedless raisin',
 'gorgonzola',
 'gouda',
 'gouda cheese',
 'graham cracker',
 'graham cracker crust',
 'grand marnier',
 'granola',
 'granulated sugar',
 'grape',
 'grape tomato',
 'grapefruit',
 'grapefruit juice',
 'gravy',
 'great northern bean',
 'greek yogurt',
 'green',
 'green bean',
 'green chili pepper',
 'green chilies',
 'green onion',
 'green pea',
 'grenadine',
 'ground coriander',
 'ground pepper',
 'ground round',
 'ground turkey',
 'gruyere',
 'gruyere cheese',
 'guacamole',
 'guinness stout',
 'gum paste',
 'habanero pepper',
 'halfandhalf',
 'halfandhalf cream',
 'halibut',
 'ham',
 'hamburger',
 'hamburger bun',
 'harissa',
 'hash brown',
 'havarti cheese',
 'hazelnut',
 'heavy cream',
 'herb',
 'herb seasoned stuffing mix',
 'herbs',
 'hoisin sauce',
 'honey',
 'honey mustard',
 'honeydew melon',
 'horseradish',
 'hot chili bean',
 'hot dog',
 'hot dog bun',
 'hot pepper',
 'hot pepper sauce',
 'hot sauce',
 'hummus',
 'ice',
 'ice cream',
 'iceberg lettuce',
 'icing',
 'instant coffee',
 'instant potato flake',
 'irish cream',
 'italian breadcrumb',
 'italian salad dressing',
 'italian sausage',
 'italian seasoning',
 'italian sweet sausage',
 'italianstyle tomato',
 'jalapeno',
 'jam',
 'jasmine rice',
 'jicama',
 'juice',
 'kaffir lime leaf',
 'kahlua',
 'kale',
 'ketchup',
 'key lime juice',
 'kidney bean',
 'kielbasa',
 'kiwi',
 'lamb',
 'lamb shank',
 'lard',
 'lasagna noodle',
 'lean pork',
 'leek',
 'leg of lamb',
 'lemon',
 'lemon extract',
 'lemon juice',
 'lemon peel',
 'lemon rind',
 'lemon zest',
 'lemonade',
 'lemongrass',
 'lentil',
 'lettuce',
 'lettuce leaf',
 'light cream',
 'light cream cheese',
 'lima bean',
 'lime',
 'lime juice',
 'lime rind',
 'lime zest',
 'limeade',
 'linguine',
 'liquid smoke',
 'long grain rice',
 'longgrain rice',
 'lowfat milk',
 'lowfat yogurt',
 'macadamia nut',
 'macaroni',
 'mace',
 'malt vinegar',
 'mandarin orange',
 'mango',
 'mango chutney',
 'manicotti',
 'maple extract',
 'maple syrup',
 'maraschino cherry',
 'margarine',
 'marinara sauce',
 'marjoram',
 'marmalade',
 'marsala wine',
 'marshmallow',
 'marshmallow cream',
 'marshmallow creme',
 'masala',
 'mascarpone cheese',
 'mashed potato',
 'matzo meal',
 'mayonnaise',
 'meat',
 'meatball',
 'mexican cheese blend',
 'midori melon liqueur',
 'milk',
 'milk powder',
 'mint',
 'miracle whip',
 'mirin',
 'mixed green',
 'mixed vegetable',
 'molasses',
 'monterey jack cheese',
 'mozzarella cheese',
 'msg',
 'muenster cheese',
 'mushroom',
 'mushroom soup',
 'mussel',
 'mustard',
 'mustard powder',
 'mustard seed',
 'napa cabbage leaf',
 'naturalstyle chunky peanut butter',
 'navy bean',
 'nectarine',
 'neufchatel cheese',
 'nonfat milk',
 'nonfat yogurt',
 'noodle',
 'nut',
 'nutella',
 'nutmeg',
 'oat',
 'oatmeal',
 'oil',
 'okra',
 'olive',
 'olive oil',
 'onion',
 'onion powder',
 'onion soup',
 'onion soup mix',
 'orange',
 'orange extract',
 'orange juice',
 'orange liqueur',
 'orange rind',
 'oregano',
 'oreo cooky',
 'original sauce',
 'orzo pasta',
 'oyster',
 'oyster sauce',
 'palm sugar',
 'pancetta',
 'papaya',
 'paprika',
 'parmesan cheese',
 'parmigianoreggiano cheese',
 'parsley',
 'parsnip',
 'pasta',
 'pasta sauce',
 'pasta shell',
 'pea',
 'peach',
 'peanut',
 'peanut butter',
 'peanut oil',
 'pear',
 'peas',
 'pecan',
 'pecorino cheese',
 'penne',
 'pepper',
 'peppercorn',
 'peppermint',
 'pepperoni',
 'pesto sauce',
 'phyllo pastry sheet',
 'picante sauce',
 'pickle',
 'pickled jalapeno pepper',
 'pie crust',
 'pie filling',
 'pie shell',
 'pillsbury refrigerated crescent dinner roll',
 'pimento',
 'pimiento',
 'pine nut',
 'pineapple',
 'pineapple juice',
 'pinto bean',
 'pistachio',
 'pita bread',
 'pizza crust',
 'pizza dough',
 'pizza sauce',
 'plain yogurt',
 'plantain',
 'plum',
 'plum tomato',
 'polenta',
 'pomegranate juice',
 'popped popcorn',
 'poppy seed',
 'pork',
 'pork chop',
 'pork sausage',
 'pork shoulder',
 'pork tenderloin steak',
 'port wine',
 'portabella mushroom',
 'potato chip',
 'powdered milk',
 'powdered sugar',
 'prawn',
 'prepared mustard',
 'pretzel',
 'prosciutto',
 'provolone cheese',
 'prune',
 'puff pastry',
 'puff pastry sheet',
 'pumpkin',
 'pumpkin pie spice',
 'pumpkin seed',
 'queso fresco',
 'quinoa',
 'radish',
 'raisin',
 'ramen noodle',
 'ranch dressing',
 'ranch salad dressing',
 'raspberry',
 'raspberry jam',
 'red chili pepper flake',
 'red hot sauce',
 'red onion',
 'red pepper',
 'red snapper',
 'red wine',
 'refried bean',
 'refrigerated biscuit',
 'rhubarb',
 'rice',
 'rice flour',
 'rice krispies',
 'rice noodle',
 'rice vermicelli',
 'rice vinegar',
 'rice wine',
 'ricotta cheese',
 'ripe olive',
 'ritz cracker',
 'ritz cracker crumb',
 'roast pork',
 'roasted garlic',
 'roasted red pepper',
 'roasting chicken',
 'roll',
 'romaine lettuce',
 'romano cheese',
 'rosemary',
 'rotel tomato',
 'rotini pasta',
 'round steak',
 'rum',
 'rum extract',
 'rutabaga',
 'rye bread',
 'rye flour',
 'saffron',
 'sage',
 'sake',
 'salad dressing',
 'salami',
 'salmon',
 'salsa',
 'salt',
 'salted butter',
 'saltine cracker',
 'sauerkraut',
 'sausage',
 'scallion',
 'scallop',
 'schnapps',
 'scotch bonnet pepper',
 'seasoning',
 'seasoning mix',
 'seedless grape',
 'selfrising flour',
 'serrano pepper',
 'sesame oil',
 'sesame seed',
 'shallot',
 'sherry wine',
 'sherry wine vinegar',
 'shiitake mushroom',
 'shortening',
 'shrimp',
 'sirloin',
 'skewer',
 'smoked salmon',
 'smoked sausage',
 'smoked streaky bacon',
 'snow pea',
 'sour cream',
 'sourdough',
 'sourdough bread',
 'soy sauce',
 'soymilk',
 'spaghetti',
 'spaghetti sauce',
 'spaghetti squash',
 'sparerib',
 'sparkling water',
 'spinach',
 'spring onion',
 'sprite',
 'squash',
 'sriracha sauce',
 'star anise',
 'starch',
 'steak',
 'steak sauce',
 'stew meat',
 'stewed tomato',
 'strawberry',
 'strawberry gelatin',
 'sugar',
 'sugar snap pea',
 'sugar substitute',
 'sugarfree instant chocolate pudding mix',
 'summer squash',
 'sundried tomato',
 'sunflower oil',
 'sunflower seed',
 'sweet corn',
 'sweet onion',
 'sweet pepper',
 'sweet potato',
 'sweet red pepper',
 'sweetened condensed milk',
 'sweetener',
 'swiss chard',
 'swiss cheese',
 'syrup',
 'tabasco sauce',
 'taco sauce',
 'taco seasoning',
 'taco shell',
 'tahini',
 'tamari',
 'tamarind paste',
 'tapioca',
 'tapioca flour',
 'tarragon',
 'tarragon vinegar',
 'tart apple',
 'tasty cheese',
 'tea',
 'tea bag',
 'tenderloin',
 'tequila',
 'teriyaki sauce',
 'thyme',
 'thyme leaf',
 'tilapia fillet',
 'toasted oat cereal',
 'toffee',
 'tofu',
 'tomatillo',
 'tomato',
 'tomato juice',
 'tomato paste',
 'tomato puree',
 'tomato sauce',
 'tomato soup',
 'toothpick',
 'tortellini',
 'tortilla',
 'tortilla flour',
 'triple sec',
 'tuna',
 'turkey',
 'turkey bacon',
 'turmeric powder',
 'turnip',
 'unsalted butter',
 'vanilla',
 'vanilla ice cream',
 'vanilla instant pudding mix',
 'vanilla pudding mix',
 'vanilla wafer',
 'veal',
 'vegetable',
 'vegetable broth',
 'vegetable oil',
 'vegetarian poultry seasoning',
 'velveeta cheese',
 'vermouth',
 'vinaigrette dressing',
 'vinegar',
 'vodka',
 'walnut',
 'walnut oil',
 'water',
 'water chestnut',
 'watercress',
 'watermelon',
 'wheat flour',
 'wheat germ',
 'whipped cream',
 'whipping cream',
 'white bean',
 'white cake mix',
 'white chocolate',
 'white flour',
 'white wine',
 'white wine vinegar',
 'whole grain bread',
 'whole wheat bread',
 'whole wheat flour',
 'whole wheat tortilla',
 'wild rice',
 'wine',
 'wine vinegar',
 'wonton wrapper',
 'worcestershire sauce',
 'wrap',
 'yam',
 'yeast',
 'yellow cake mix',
 'yellow food coloring paste',
 'yellow onion',
 'yellow pepper',
 'yellow squash',
 'yoghurt',
 'yogurt',
 'ziti pasta',
 'zucchini']

# Dictionnaire de recettes
recipe_data = {
    'cream cheese bacon croissant': 414376,
    'cheesy meatball basil tomato sauce': 331985,
    'ramen sesame oriental salad': 420508,
    'fantasy peanut butter fudge': 271993,
    'honey roast onion': 80377,
    'turkey curry peanut sauce': 143495,
    'perfect honey cake': 139651,
    'walnut icebox kipfels': 265656,
    'brown rice jambalaya': 74579,
    'spice baby carrot': 226276,
    'coffee banana scone': 257068,
    'koolaid pie': 106096,
    'mozzarella tomato salad italian basil salad dress': 289599,
    'east meet west vegetable soba stir fry': 380551,
    'guilt free onion soup crock pot': 275840,
    'grandma norwegian kringla': 347906,
    'moo goo gai pan mah gu gai pin': 100359,
    'chicken potato florentine soup olive garden': 471979,
    'baked salmon black olive salsa': 164804,
    'razzy martini': 321267,
    'pineapple souffle': 339840,
    'surdyk greek orzo salad': 131009,
    'best potato chip cooky': 122964,
    'ratatouille bake weight watcher': 412275,
    'quick easy diabetic tiramisu': 115213,
    'dessert cake namur gateau namurois': 425018,
    'utterly deadly southern pecan pie': 101954,
    'dream coffee cake': 372510,
}

st.sidebar.image(r'pexels-pixabay-33242.jpg', use_column_width=True)

def display_results(results):
    suggestions = results.get('suggestions', [])
    for suggestion in suggestions:
        recipe_id, recipe_name, recipe_url = suggestion['index'], suggestion['name'], suggestion['url']
        st.markdown(f"""
            <div style="border: 1px solid #ddd; border-radius: 10px; padding: 10px; margin: 10px 0;">
                <a href="{recipe_url}" target="_blank" style="text-decoration: none;">
                    <h3>{recipe_name}</h3>
                    <p>ID: {recipe_id}</p>
                </a>
            </div>
        """, unsafe_allow_html=True)

# Initialisation de l'état de la session pour suivre la page courante
if 'page' not in st.session_state:
    st.session_state.page = "Get recipe recomandation"

# Barre latérale pour la navigation avec des boutons
st.sidebar.title("Recettes et sentiments")
if st.sidebar.button("Get recipe recomandation"):
    st.session_state.page = "Get recipe recomandation"
if st.sidebar.button("Discover recipes"):
    st.session_state.page = "Discover recipes"

# Fonction pour valider les tags
def validate_tags(selected_tags, valid_tags):
    return all(tag in valid_tags for tag in selected_tags)

# Affichage conditionnel basé sur la page sélectionnée
if st.session_state.page == "Get recipe recomandation":
    st.header("Welcome to Recettes et sentiments")
    st.subheader('Give us a recipe, we\'ll find you something similar')
    # Formulaire avec un champ de saisie auto-complété basé sur les clés du dictionnaire recipe_data
    recipe_name = st.selectbox('Select: ', list(recipe_data.keys()))

    if st.button('Submit'):
        recipe_id = recipe_data.get(recipe_name, None)
        if recipe_id is not None:
            # Construire l'URL avec l'ID de recette sélectionnée
            url = f"https://recettes-et-sentiments-api-p4x6pl7fiq-ew.a.run.app/model_w2vec_similar_to_recipe?recipe_id={recipe_id}"
            # Envoyer la requête GET
            response = requests.get(url)
            if response.status_code == 200:
                results = response.json()
                display_results(results)
            else:
                st.error(f"Request error : {response.status_code}")
        else:
            st.error("Recipe non found")

elif st.session_state.page == "Discover recipes":
    st.header('Looking for inspiration?')
    st.subheader('Get a recipe recommendation based on: ')

    # Radio button pour la sélection du modèle
    modelSelection = st.radio(label='',
                              options=['Theme', 'Ingredients', 'Theme & Ingredients'],
                              horizontal=True)

    # Affichage conditionnel basé sur la sélection du modèle
    if modelSelection == 'Theme':
        tag_inputs = {}
        for index, row in df_tags.iterrows():
            tag_inputs[row['Categorie']] = stt.st_tags(
                label=f'Select by {row["Categorie"]}',
                suggestions=row['Tags'],
            )

        if st.button('Submit'):
            query = []
            for category, tags in tag_inputs.items():
                if validate_tags(tags, df_tags.loc[df_tags['Categorie'] == category, 'Tags'].values[0]):
                    query.extend(tags)

            # Construire l'URL de requête
            query_str = "%20".join(query)
            url = f"https://recettes-et-sentiments-api-p4x6pl7fiq-ew.a.run.app/model_w2vec_query_recipe_with_tags?query={query_str}"
            # Envoyer la requête GET
            response = requests.get(url)
            if response.status_code == 200:
                results = response.json()
                display_results(results)
            else:
                st.error(f"Rquest Error: {response.status_code}")

    elif modelSelection == 'Ingredients':
        ingredients_input = stt.st_tags(
            label='Select ingredients',
            suggestions=ingredients_list,
        )

        if st.button('Submit'):
            if validate_tags(ingredients_input, ingredients_list):
                query_str = "%20".join(ingredients_input)
                url = f"https://recettes-et-sentiments-api-p4x6pl7fiq-ew.a.run.app/model_w2vec_query_recipe_with_ingredients?query={query_str}"
                response = requests.get(url)
                if response.status_code == 200:
                    results = response.json()
                    display_results(results)
                else:
                    st.error(f"Request error : {response.status_code}")
            else:
                st.error('Vous avez entré un ou plusieurs ingrédients invalides')

    elif modelSelection == 'Theme & Ingredients':
        tag_inputs = {}
        for index, row in df_tags.iterrows():
            tag_inputs[row['Categorie']] = stt.st_tags(
                label=f'Select tags for {row["Categorie"]}',
                suggestions=row['Tags'],
            )

        ingredients_input = stt.st_tags(
            label='Select ingredients',
            suggestions=ingredients_list,
        )

        if st.button('Submit'):
            all_valid = True
            query = []
            for category, tags in tag_inputs.items():
                if validate_tags(tags, df_tags.loc[df_tags['Categorie'] == category, 'Tags'].values[0]):
                    query.extend(tags)
                else:
                    st.error(f'You have imputed at least one invalid tags for {category}')
                    all_valid = False

            if validate_tags(ingredients_input, ingredients_list):
                query.extend(ingredients_input)
            else:
                st.error('You have imputed at least one invalid ingredients')
                all_valid = False

            if all_valid:
                query_str = "%20".join(query)
                url = f"https://recettes-et-sentiments-api-p4x6pl7fiq-ew.a.run.app/model_w2vec_query_recipe_with_tags_and_ingredients?query={query_str}"
                response = requests.get(url)
                if response.status_code == 200:
                    results = response.json()
                    display_results(results)
                else:
                    st.error(f"Request error : {response.status_code}")
